from typing import Final

PROTOCOL_VERSION: Final = 3
AUDIENCE_CONTRACT_VERSION: Final = 3
TRACE_SCHEMA_VERSION: Final = 1
REPLAY_SCHEMA_VERSION: Final = 1
PROTOCOL_VERSION_HEADER: Final = "X-ADVX-Protocol-Version"
